#!/usr/bin/env python3
"""
Integration Module for Enhanced Visualizations with Compliance Audit Engine
"""

import logging
from pathlib import Path
from datetime import datetime
import sys
import os

# Add parent directory to path to import improved_visualizations
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from test2.improved_visualizations import (
    generate_improved_trend_analysis,
    generate_interactive_trend_dashboard,
    generate_enhanced_heatmap
)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class VisualizationIntegrator:
    """
    Integrates enhanced visualizations with the Compliance Audit Engine
    """
    
    def __init__(self, auditor):
        """
        Initialize the integrator with a reference to the compliance auditor
        
        Args:
            auditor: Instance of EnhancedComplianceAuditor
        """
        self.auditor = auditor
        self.output_dir = auditor.output_dir
        self.charts_dir = auditor.charts_dir
        self.historical_dir = auditor.historical_dir
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    def generate_all_enhanced_visualizations(self):
        """
        Generate all enhanced visualizations to replace the default ones
        
        Returns:
            Dictionary containing paths to all generated visualizations
        """
        logger.info("Generating enhanced visualizations...")
        
        # Create output paths
        for dir_path in [self.output_dir, self.charts_dir]:
            Path(dir_path).mkdir(exist_ok=True)
        
        # Generate enhanced heatmap
        heatmap_path = generate_enhanced_heatmap(
            self.auditor.results,
            self.charts_dir,
            self.timestamp
        )
        
        # Generate improved trend analysis
        trend_path = generate_improved_trend_analysis(
            self.historical_dir,
            self.charts_dir,
            self.timestamp
        )
        
        # Generate interactive trend dashboard
        dashboard_path = generate_interactive_trend_dashboard(
            self.historical_dir,
            self.charts_dir,
            self.timestamp
        )
        
        # Return paths to all generated visualizations
        return {
            'enhanced_heatmap': heatmap_path,
            'improved_trend_analysis': trend_path,
            'interactive_dashboard': dashboard_path
        }
    
    def enhance_excel_report(self, excel_file):
        """
        Enhance the Excel report with additional details and visualizations
        
        Args:
            excel_file: Path to the Excel file generated by the auditor
            
        Returns:
            Path to the enhanced Excel file
        """
        import pandas as pd
        from openpyxl import load_workbook
        from openpyxl.drawing.image import Image
        from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
        from openpyxl.utils import get_column_letter
        
        logger.info(f"Enhancing Excel report: {excel_file}")
        
        # Load the workbook
        wb = load_workbook(excel_file)
        
        # Add a new sheet for gap analysis
        if 'Gap_Analysis' not in wb.sheetnames:
            gap_sheet = wb.create_sheet('Gap_Analysis')
            
            # Set up headers
            headers = [
                'Company', 'Framework', 'Category', 'Current Compliance %', 
                'Target Compliance %', 'Gap', 'Priority', 'Estimated Effort', 
                'Recommended Actions'
            ]
            
            for col, header in enumerate(headers, 1):
                cell = gap_sheet.cell(row=1, column=col)
                cell.value = header
                cell.font = Font(bold=True, color="FFFFFF")
                cell.fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
                cell.alignment = Alignment(horizontal='center', vertical='center')
            
            # Format the sheet
            for col in range(1, len(headers) + 1):
                gap_sheet.column_dimensions[get_column_letter(col)].width = 15
            
            # Add gap analysis data
            row = 2
            for company, frameworks in self.auditor.results.items():
                for framework, metrics in frameworks.items():
                    if framework != 'overall':
                        for category, stats in metrics.get('category_breakdown', {}).items():
                            current = stats.get('compliance_pct', 0)
                            target = 85  # Default target (LOW risk threshold)
                            gap = target - current
                            
                            if gap <= 0:
                                continue  # Skip if already meeting target
                            
                            # Determine priority based on gap size
                            if gap > 50:
                                priority = "Critical"
                                fill_color = "FF4444"  # Red
                            elif gap > 25:
                                priority = "High"
                                fill_color = "FFA500"  # Orange
                            else:
                                priority = "Medium"
                                fill_color = "FFD700"  # Yellow
                            
                            # Estimate effort based on gap size
                            if gap > 50:
                                effort = "High (1-2 months)"
                            elif gap > 25:
                                effort = "Medium (2-4 weeks)"
                            else:
                                effort = "Low (1-2 weeks)"
                            
                            # Add row data
                            gap_sheet.cell(row=row, column=1).value = company
                            gap_sheet.cell(row=row, column=2).value = framework
                            gap_sheet.cell(row=row, column=3).value = category
                            gap_sheet.cell(row=row, column=4).value = current
                            gap_sheet.cell(row=row, column=5).value = target
                            gap_sheet.cell(row=row, column=6).value = gap
                            
                            # Format gap cell with color
                            gap_cell = gap_sheet.cell(row=row, column=6)
                            gap_cell.fill = PatternFill(start_color=fill_color, end_color=fill_color, fill_type="solid")
                            gap_cell.font = Font(color="FFFFFF" if gap > 25 else "000000", bold=True)
                            
                            gap_sheet.cell(row=row, column=7).value = priority
                            gap_sheet.cell(row=row, column=8).value = effort
                            
                            # Add recommended actions based on category
                            actions = self._get_recommended_actions(category, gap)
                            gap_sheet.cell(row=row, column=9).value = actions
                            
                            row += 1
        
        # Add a new sheet for executive summary with visualizations
        if 'Executive_Dashboard' not in wb.sheetnames:
            exec_sheet = wb.create_sheet('Executive_Dashboard', 0)  # Insert at the beginning
            
            # Add title
            exec_sheet.merge_cells('A1:J1')
            title_cell = exec_sheet.cell(row=1, column=1)
            title_cell.value = "COMPLIANCE AUDIT EXECUTIVE DASHBOARD"
            title_cell.font = Font(size=16, bold=True, color="1F4E79")
            title_cell.alignment = Alignment(horizontal='center', vertical='center')
            
            # Add summary statistics
            exec_sheet.merge_cells('A3:E3')
            exec_sheet.cell(row=3, column=1).value = "SUMMARY STATISTICS"
            exec_sheet.cell(row=3, column=1).font = Font(size=12, bold=True)
            
            # Calculate summary statistics
            total_companies = len(self.auditor.results)
            avg_compliance = sum(comp['overall']['compliance_percentage'] for comp in self.auditor.results.values()) / total_companies
            critical_issues = sum(comp['overall']['total_critical_issues'] for comp in self.auditor.results.values())
            high_issues = sum(comp['overall']['total_high_issues'] for comp in self.auditor.results.values())
            
            # Add statistics
            stats = [
                ("Total Organizations Assessed", total_companies),
                ("Average Compliance Score", f"{avg_compliance:.1f}%"),
                ("Critical Security Issues", critical_issues),
                ("High Priority Issues", high_issues),
                ("Total Priority Issues", critical_issues + high_issues)
            ]
            
            for i, (label, value) in enumerate(stats):
                exec_sheet.cell(row=4+i, column=1).value = label
                exec_sheet.cell(row=4+i, column=2).value = value
                exec_sheet.cell(row=4+i, column=1).font = Font(bold=True)
            
            # Add space for visualizations
            exec_sheet.row_dimensions[10].height = 20  # Spacer
            
            # Add note about visualizations
            exec_sheet.merge_cells('A11:J11')
            exec_sheet.cell(row=11, column=1).value = "ENHANCED VISUALIZATIONS (See charts directory for detailed visualizations)"
            exec_sheet.cell(row=11, column=1).font = Font(size=12, bold=True)
            
            # Add instructions to view interactive dashboard
            exec_sheet.merge_cells('A13:J13')
            exec_sheet.cell(row=13, column=1).value = "For interactive dashboards, open the HTML files in the charts directory with a web browser"
            exec_sheet.cell(row=13, column=1).font = Font(italic=True)
        
        # Add a new sheet for remediation tracking
        if 'Remediation_Tracking' not in wb.sheetnames:
            track_sheet = wb.create_sheet('Remediation_Tracking')
            
            # Set up headers
            headers = [
                'Company', 'Framework', 'Rule ID', 'Description', 'Status', 
                'Assigned To', 'Due Date', 'Progress', 'Notes', 'Verification Method'
            ]
            
            for col, header in enumerate(headers, 1):
                cell = track_sheet.cell(row=1, column=col)
                cell.value = header
                cell.font = Font(bold=True, color="FFFFFF")
                cell.fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
                cell.alignment = Alignment(horizontal='center', vertical='center')
            
            # Format the sheet
            for col in range(1, len(headers) + 1):
                track_sheet.column_dimensions[get_column_letter(col)].width = 15
            
            # Add template rows for failed rules
            row = 2
            for company, frameworks in self.auditor.results.items():
                for framework, metrics in frameworks.items():
                    if framework != 'overall':
                        for rule in metrics.get('rule_details', []):
                            if rule['status'] in ['FAIL', 'MISSING_DATA', 'ERROR']:
                                # Add row data
                                track_sheet.cell(row=row, column=1).value = company
                                track_sheet.cell(row=row, column=2).value = framework
                                track_sheet.cell(row=row, column=3).value = rule.get('rule_id', 'N/A')
                                track_sheet.cell(row=row, column=4).value = rule.get('description', 'N/A')
                                track_sheet.cell(row=row, column=5).value = "Open"
                                
                                # Add dropdown for status
                                # Note: This requires more complex openpyxl data validation setup
                                
                                # Add due date based on severity
                                severity = rule.get('severity', 'MEDIUM')
                                if severity == 'CRITICAL':
                                    due_days = 7
                                elif severity == 'HIGH':
                                    due_days = 30
                                elif severity == 'MEDIUM':
                                    due_days = 60
                                else:
                                    due_days = 90
                                
                                due_date = datetime.now() + timedelta(days=due_days)
                                track_sheet.cell(row=row, column=7).value = due_date.strftime("%Y-%m-%d")
                                
                                # Add progress cell (0%)
                                track_sheet.cell(row=row, column=8).value = "0%"
                                
                                # Add verification method based on rule type
                                category = rule.get('category', 'General')
                                if 'Configuration' in category:
                                    verify = "Configuration Review"
                                elif 'Network' in category:
                                    verify = "Network Scan"
                                elif 'Access' in category:
                                    verify = "Access Control Audit"
                                else:
                                    verify = "Manual Verification"
                                
                                track_sheet.cell(row=row, column=10).value = verify
                                
                                row += 1
        
        # Save the enhanced workbook
        enhanced_file = str(excel_file).replace('.xlsx', '_enhanced.xlsx')
        wb.save(enhanced_file)
        logger.info(f"Enhanced Excel report saved to: {enhanced_file}")
        
        return enhanced_file
    
    def _get_recommended_actions(self, category, gap):
        """Helper method to get recommended actions based on category and gap size"""
        if 'Access Control' in category:
            return "Implement role-based access controls and regular access reviews"
        elif 'Configuration' in category:
            return "Apply security baselines and implement configuration management"
        elif 'Network' in category:
            return "Implement network segmentation and enhanced firewall rules"
        elif 'Logging' in category:
            return "Deploy centralized logging and monitoring solution"
        elif 'Vulnerability' in category:
            return "Implement regular vulnerability scanning and patch management"
        else:
            return "Review compliance requirements and implement controls"

def integrate_with_auditor(auditor):
    """
    Integrate enhanced visualizations with an existing auditor instance
    
    Args:
        auditor: Instance of EnhancedComplianceAuditor
        
    Returns:
        Dictionary containing paths to enhanced outputs
    """
    integrator = VisualizationIntegrator(auditor)
    
    # Generate enhanced visualizations
    viz_paths = integrator.generate_all_enhanced_visualizations()
    
    # Enhance Excel report if it exists
    excel_files = list(Path(auditor.output_dir).glob("comprehensive_compliance_report_*.xlsx"))
    if excel_files:
        latest_excel = max(excel_files, key=lambda p: p.stat().st_mtime)
        enhanced_excel = integrator.enhance_excel_report(latest_excel)
        viz_paths['enhanced_excel'] = enhanced_excel
    
    return viz_paths

if __name__ == "__main__":
    # Example usage
    import sys
    from compliance_audit_engine import EnhancedComplianceAuditor
    
    # Create and run auditor
    auditor = EnhancedComplianceAuditor()
    results = auditor.run_comprehensive_audit()
    
    # Integrate enhanced visualizations
    viz_paths = integrate_with_auditor(auditor)
    
    print("\nEnhanced Visualizations Generated:")
    for name, path in viz_paths.items():
        print(f"- {name}: {path}")